server: 
  port: ${PORT:8761}
  
eureka:
#  server: 
#     enableSelfPreservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false   # 禁用客户端注册行为
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#---
#spring:
#  profiles: serv1.euroke.colorcc.com
#eureka:
#  instance:
#    hostname: serv1.euroke.colorcc.com
#  client:
#    registerWithEureka: false   # 禁用客户端注册行为
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://serv2.euroke.colorcc.com:8762/eureka/
#---
#spring:
#  profiles: serv2.euroke.colorcc.com
#eureka:
#  instance:
#    hostname: serv2.euroke.colorcc.com
#  client:
#    registerWithEureka: false   # 禁用客户端注册行为
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://serv1.euroke.colorcc.com:8761/eureka/