server: 
  port: ${PORT:8081}
  
spring:
  application:
    name: colorcc-biz-provider
  
eureka:
  instance: 
    instanceId:  ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
logging:
  level:
    com.colorcc.cloud: DEBUG