server: 
  port: ${PORT:9411}
#  enableSelfPreservation: false
 
spring: 
  application: 
    name: biz-consumer-ribbon
  cloud: 
    zookeeper: 
      connectString: 192.168.1.106:2181
    stream: 
      kafka: 
        binder: 
          zk-nodes: 192.168.1.106 
          brokers: 192.168.1.106 
  zipkin:
    base-url: http://localhost:9411/  #spring-cloud-sleuth-zipkin
  sleuth:
    stream:
      enabled: false
    sampler:
      percentage: 0.5

zipkin:
  collector: 
    kafka: 
      zookeeper: 192.168.1.106:2181   # spring-cloud-stream-binder-kafka
  
eureka:
  instance: colorcc-biz-consumer-ribbon
  client:
#    availabilityZones: 
#      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}} 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
  
# ribbon 请求 provider 对应的  spring.applicaiton.name ，供  LoadBalancer 时从 Eureka 查对应的服务用
provider: 
  name: colorcc-biz-provider
  
colorcc-biz-consumer-ribbon: 
  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:8081,localhost:8082
    ServerListRefreshInterval: 1000
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true

zuul:
  ignoredServices: '*'
  routes:
    biz-consumer-ribbon: /jack/**   #http://localhost:8093/jack/hello  --> http://localhost:8093/hello

#zuul: 
#  routes: 
#    biz-consumer-ribbon: 
#      url: http://localhost:8082
    