server: 
  port: ${PORT:8093}
#  enableSelfPreservation: false
  
spring:
  application:
    name: biz-consumer-ribbon
  
eureka:
  instance: colorcc-biz-consumer-ribbon
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
colorcc-biz-provider:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:8082
    ServerListRefreshInterval: 15000